<a href="https://colab.research.google.com/github/MaineCalabrezi13/EstatisticaAplicada/blob/main/Copy_of_AmostragemSimples_Sistematica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import random
import numpy as np

In [10]:
dataset=pd.read_csv('census.csv', delimiter=';')

In [11]:
dataset.shape

(32561, 15)

In [ ]:
dataset.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
dataset.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
df_amostra_aleatoria_simples = dataset.sample(n = 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [ ]:
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
24274,67,Self-emp-not-inc,123393,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,6418,0,58,United-States,>50K
22443,44,Private,210013,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,>50K
19595,51,Private,87205,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,7688,0,20,United-States,>50K
2837,69,Self-emp-not-inc,69306,Some-college,10,Married-civ-spouse,Other-service,Wife,White,Female,0,0,15,United-States,<=50K
4028,26,Private,195216,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,12,United-States,<=50K

In [ ]:
df_amostra_aleatoria_simples = dataset.sample(n = 100,)
df_amostra_aleatoria_simples.shape

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
15178,27,Private,369522,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,45,United-States,<=50K
14091,25,Private,169124,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
5077,35,Private,170797,Bachelors,13,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
24910,55,Local-gov,171328,Some-college,10,Married-spouse-absent,Adm-clerical,Unmarried,Black,Female,0,0,35,United-States,<=50K
19089,58,Federal-gov,30111,Some-college,10,Widowed,Prof-specialty,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K

In [ ]:
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
15178,27,Private,369522,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,45,United-States,<=50K
14091,25,Private,169124,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
5077,35,Private,170797,Bachelors,13,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
24910,55,Local-gov,171328,Some-college,10,Married-spouse-absent,Adm-clerical,Unmarried,Black,Female,0,0,35,United-States,<=50K
19089,58,Federal-gov,30111,Some-college,10,Widowed,Prof-specialty,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K

In [ ]:
df_amostra_aleatoria_simples = dataset.sample(n = 100, random_state= 1)
df_amostra_aleatoria_simples.shape

(100, 15)

In [ ]:
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

In [ ]:
def df_amostra_aleatoria_simples(dataset, amostras):
  return dataset.sample(n = amostras)

In [ ]:
df_amostra_aleatoria_simples = df_amostra_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [ ]:
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
27397,32,Local-gov,114733,Bachelors,13,Divorced,Prof-specialty,Unmarried,White,Female,0,0,35,United-States,<=50K
17618,25,Private,108301,HS-grad,9,Separated,Other-service,Unmarried,White,Female,0,0,20,United-States,<=50K
25844,29,Private,367329,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
5399,32,Private,53260,HS-grad,9,Divorced,Other-service,Unmarried,Other,Female,0,0,28,United-States,<=50K
14409,28,Private,301654,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,<=50K

In [ ]:
def amostragem_aleatoria_simples(dataset, amostras):
  return dataset.sample(n = amostras, random_state=1)

In [ ]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [ ]:
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
9646,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
709,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
7385,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
16671,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
21932,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

In [ ]:
def amostragem_aleatoria_simples(dataset, amostras):
  return dataset.sample(n = amostras, random_state=2)

In [ ]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [ ]:
df_amostra_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
16054,42,State-gov,160369,HS-grad,9,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,>50K
32382,44,Local-gov,150171,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
10749,39,Local-gov,256997,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
15377,39,Private,147548,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29660,29,Federal-gov,106179,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Female,0,1408,40,United-States,<=50K

In [ ]:
dataset.shape

(32561, 15)

In [ ]:
len(dataset)

32561

In [ ]:
dataset.shape

(32561, 15)

In [ ]:
len(dataset)/100

325.61

In [ ]:
dataset.shape

(32561, 15)

In [ ]:
len(dataset)//100

325

In [ ]:
dataset.shape

(32561, 15)

In [ ]:
len(dataset)//100

325

In [ ]:
random.randint(0,325)

23

In [ ]:
dataset.shape

(32561, 15)

In [ ]:
len(dataset)//100

325

In [ ]:
random.seed(1)
random.randint(0,325)

68

In [ ]:
dataset.shape

(32561, 15)

In [ ]:
len(dataset)//100

325

In [ ]:
random.seed(1)
random.randint(0,325)

68

In [ ]:
68+325

393

In [ ]:
len(dataset)//100

325

In [ ]:
random.seed(1)
random.randint(0,325)

68

In [ ]:
68 + 325

393

In [ ]:
393+325

718

In [1]:
68+325

393

In [2]:
393+325

718

In [12]:
np.arange(68, len(dataset), step=325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [17]:
def amostragem_sistematica(dataset, amostras):
  intervalo = len(dataset) // amostras
  random.seed(1)
  inicio = random.randint(0, intervalo)
  indices = np.arange(inicio, len(dataset), step = intervalo)
  amostragem_sistematica = dataset.iloc[indices]
  return amostragem_sistematica

In [18]:
df_amostra_sistematica = amostragem_sistematica(dataset,100)
df_amostra_sistematica.shape

(100, 15)

In [19]:
df_amostra_sistematica.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
68,49,Self-emp-inc,191681,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
393,34,State-gov,98101,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,45,?,>50K
718,22,Private,214399,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,15,United-States,<=50K
1043,44,Private,167005,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,60,United-States,>50K
1368,52,Private,152234,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,99999,0,40,Japan,>50K